name: Pull Request

on:
  push:
    branches:
    - feature/'*'

  pull_request:
    branches:
    - develop


jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [13]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: Restore Lerna node modules
      uses: actions/cache@master
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

    - name: Install Packages
      run: yarn install --frozen-lock-file

    - name: Lint
      run: yarn lint

    - name: Test
      run: yarn coverage

    - name: Coverage
      if: matrix.os == 'ubuntu-latest' # Only run coverage on ubuntu
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        file: ./packages/api/coverage/lcov.info # optional
        flags: unittests # optional
        fail_ci_if_error: true # optional (default = false)
